### ISSUE TITLE
Retrieving data from EVE-central

### ISSUE THREAD

**Issue by jowind** [theatrus/eve-central.com#15]
There seems to be an issue with the format in Eve-Central.

Using this: 
http://api.eve-central.com/api/marketstat?typeid=37&usesystem=30002510,/evec_api/marketstat/type/sell/min
I get an error like this the following:

oooooooooooooooooooooooooooooooooooooooooooooooooooooo
An internal error occurred. Here is a debugging stacktrace. 
Please report issues to https://github.com/theatrus/eve-central.com

java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
java.lang.Long.parseLong(Long.java:441)
java.lang.Long.parseLong(Long.java:483)
scala.collection.immutable.StringLike$class.toLong(StringLike.scala:230)
scala.collection.immutable.StringOps.toLong(StringOps.scala:31)
com.evecentral.ParameterHelper$$anonfun$singleParam$1.apply(ParameterHelper.scala:44)
com.evecentral.ParameterHelper$$anonfun$singleParam$1.apply(ParameterHelper.scala:44)
scala.Option.map(Option.scala:145)
com.evecentral.ParameterHelper$.singleParam(ParameterHelper.scala:44)
com.evecentral.api.MarketStatActor$$anonfun$receive$2.applyOrElse(APIv2Service.scala:210)
akka.actor.Actor$class.aroundReceive(Actor.scala:465)
com.evecentral.api.MarketStatActor.aroundReceive(APIv2Service.scala:168)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
akka.actor.ActorCell.invoke(ActorCell.scala:487)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
akka.dispatch.Mailbox.run(Mailbox.scala:220)
akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Using the formula in Google docs:
=importXML("https://eve-central.com/api/marketstat?usesystem=30002053&typeid=37","//type/sell/min")

gives the error #Value

Hope you can help !!

**Comment by theatrus** [comment]
Cool!
