### ISSUE TITLE
Previously working importxml() call now generating an internal error

### ISSUE THREAD

**Issue by francoisgervais** [theatrus/eve-central.com#16]
Hello,

This is what I'm calling:
=ImportXML("http://api.eve-central.com/api/marketstat?typeid=37&typeid=40&typeid=36&typeid=11399&typeid=38&typeid=35&typeid=34&typeid=39&usesystem=30000142","//marketstat/type/buy")

This is what I'm getting:
An internal error occurred. Here is a debugging stacktrace. 
Please report issues to https://github.com/theatrus/eve-central.com

java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
java.lang.Long.parseLong(Long.java:589)
java.lang.Long.parseLong(Long.java:631)
scala.collection.immutable.StringLike$class.toLong(StringLike.scala:230)
scala.collection.immutable.StringOps.toLong(StringOps.scala:31)
com.evecentral.ParameterHelper$$anonfun$singleParam$1.apply(ParameterHelper.scala:44)
com.evecentral.ParameterHelper$$anonfun$singleParam$1.apply(ParameterHelper.scala:44)
scala.Option.map(Option.scala:145)
com.evecentral.ParameterHelper$.singleParam(ParameterHelper.scala:44)
com.evecentral.api.MarketStatActor$$anonfun$receive$2.applyOrElse(APIv2Service.scala:210)
akka.actor.Actor$class.aroundReceive(Actor.scala:467)
com.evecentral.api.MarketStatActor.aroundReceive(APIv2Service.scala:168)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
akka.actor.ActorCell.invoke(ActorCell.scala:487)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
akka.dispatch.Mailbox.run(Mailbox.scala:221)
akka.dispatch.Mailbox.exec(Mailbox.scala:231)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by francoisgervais** [comment]
Clearing the cell and pasting in the formula again works, however let me know if I'm doing something naughty.

**Comment by theatrus** [comment]
Your query looks just fine - the error would imply the system or type isn't a number, which they all appear to be.

Let me know if this happens again as its pretty strange.
